default: &default
    api_key: 'zNWEIzPJ0tYSbCCYAE7bw'
    consumer_key: 'zNWEIzPJ0tYSbCCYAE7bw'
    consumer_secret: 'RMS8HvZLE2rBQWAyJXQ6TwB7yPACQOtCU4CGa7RzGJs'

development:
    api_key: 'haEiBqKxMKmTlD7HxB4Q'
    consumer_key: 'haEiBqKxMKmTlD7HxB4Q'
    consumer_secret: 'rmbjToXaYDaU79IQ72ZlyzqffpV0PtSmmF9pa5Fb8'

test:
    <<: *default

production:
    <<: *default