default: &default
    api_key: ''
    consumer_key: ''
    consumer_secret: ''

development:
    api_key: ''
    consumer_key: ''
    consumer_secret: ''

test:
    <<: *default

production:
    <<: *default